services:
  - type: web
    name: binance-futures-bot
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
